{
"all_themes": [
    {
     "card1": "ILYN_INCA;LSSK_SPGT;ARHJ_ICARUS;ILMJ_INCA;KIJL_REM;KINT_REM;KKKY_404;NWSO_STDY;BMPH_PSYC;NWRK_STDY;KKHU_404;NWYS_STDY;CTJA_GO;CTMT_GO;ENHS_KNIFE;ENJA_KNIFE;BMAS_PSYC;ENJK_KNIFE;P1JS_UNIQ;P1JI_UNIQ;ARJS_ICARUS",
     "card2": "LSEC_SPGT;ARHS_ICARUS;ILWH_INCA;LSCW_SPGT;ILMK_INCA;KIBE_REM;NWJH_STDY;NWRY_STDY;CTJU_GO;ENSH_KNIFE;BMRK_PSYC;BMRR_PSYC;ENSN_KNIFE;P1TH_UNIQ;P1KH_UNIQ;BMAH_PSYC",
     "card3": "ILIR_INCA;LSYJ_SPGT;LSKZ_SPGT;KKLS_404;KKSU_404;KKJI_404;KIHN_REM;ARKL_ICARUS;ARCH_ICARUS;NWSK_STDY;CTSH_GO;CTKH_GO;BMCQ_PSYC;ENJW_KNIFE;ENNK_KNIFE;P1SO_UNIQ;P1IN_UNIQ"
      }
      ]
                             }
