{
"all_themes": [
    {
     "card1": "ILYN_INCA;ARHJ_ICARUS;ILMJ_INCA;KIJL_REM;KINT_REM;NWSO_STDY;NWRK_STDY;NWYS_STDY;CTJA_GO;CTMT_GO;ENHS_KNIFE;ENJA_KNIFE;ENJK_KNIFE;P1JS_UNIQ;P1JI_UNIQ;ARJS_ICARUS",
     "card2": "ARHS_ICARUS;ILWH_INCA;ILMK_INCA;KIBE_REM;NWJH_STDY;NWRY_STDY;CTJU_GO;ENSH_KNIFE;ENSN_KNIFE;P1TH_UNIQ;P1KH_UNIQ",
     "card3": "ILIR_INCA;KIHN_REM;ARKL_ICARUS;ARCH_ICARUS;NWSK_STDY;CTSH_GO;CTKH_GO;ENJW_KNIFE;ENNK_KNIFE;P1SO_UNIQ;P1IN_UNIQ"
      }
      ]
                             }
