{
"all_themes": [
    {
     "card1": "IDPA_TRAS_BETA_01;IDPA_LSYJ_BETA_01;IDPA_CLKS_BETA_01;IDPA_SACA_BETA_01",
     "card2": "IDPA_SACA_BETA_01;IDPA_CLKS_BETA_01;IDPA_LSYJ_BETA_01;IDPA_TRAS_BETA_01",
     "card3": "IDPA_CLKS_BETA_01;IDPA_TRAS_BETA_01;IDPA_SACA_BETA_01;IDPA_LSYJ_BETA_01"
      }
      ]
                             }
